# Generated by Django 5.1.2 on 2024-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], max_length=25)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('pays', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('Assistant', 'Assistant'), ('MAB', 'MAB'), ('MAA', 'MAA'), ('MCB', 'MCB'), ('MCA', 'MCA'), ('Professeur', 'Professeur')], max_length=50)),
                ('specialite', models.CharField(choices=[('Informatique', 'Informatique'), ('Mathématiques', 'Mathématiques'), ('Anglais', 'Anglais'), ('Autres', 'Autres')], max_length=50)),
                ('university', models.ManyToManyField(to='teacher_app.university')),
            ],
        ),
    ]
