# Generated by Django 5.1.2 on 2024-11-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nationalite', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], max_length=25)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('localite', models.CharField(max_length=100)),
                ('no_postal', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macintoch', 'Macintosh'), ('unix', 'Unix')], max_length=255)),
                ('application', models.CharField(choices=[('Bureautique', 'Bureautique'), ('Daw', 'Daw'), ('Poo', 'Poo'), ('SGBD', 'SGBD'), ('Internet', 'Internet'), ('System', 'System')], max_length=255)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.filiere')),
                ('sports', models.ManyToManyField(to='student.sport')),
            ],
        ),
    ]
