# Generated by Django 5.1.2 on 2024-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
